#!/bin/sh

echo "Docker set up on $KAMAL_HOSTS..."

# https://github.com/basecamp/kamal/issues/980
# assuming KAMAL_SERVICE is identical to the host specified in .ssh/config
# NOTE: this requires the deploy SSH user to have passwordless sudo on the server
# (see README "pre-deployment prerequisites").
ssh $KAMAL_SERVICE 'sudo usermod -aG docker ${USER}'
