# https://guides.rubyonrails.org/configuring.html#database-pooling
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: sas145
  password: qwerty
  database: tg_bot_dnd_spells_2024_development

test:
  <<: *default
  username: sas145
  password: qwerty
  database: tg_bot_dnd_spells_2024_test

production:
  <<: *default
  database: tg_bot_dnd_spells_2024
  url: <%= ENV['RAILS_ENV'] == 'production' ? ENV["DATABASE_URL"] : 'http://localhost:3000/' %>
