# https://guides.rubyonrails.org/configuring.html#database-pooling
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tg_bot_dnd_spells_2024_development

test:
  <<: *default
  database: tg_bot_dnd_spells_2024_test

production:
  <<: *default
  database: tg_bot_dnd_spells_2024_production
  username: tg_bot_dnd_spells_2024
  password: <%= ENV["TG_BOT_DND_SPELLS_2024_DATABASE_PASSWORD"] %>
