# https://guides.rubyonrails.org/configuring.html#database-pooling
default: &default
  adapter: postgresql
  encoding: unicode
  username: sas145
  password: qwerty
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tg_bot_dnd_spells_2024_development

test:
  <<: *default
  database: tg_bot_dnd_spells_2024_test

production:
  <<: *default
  database: tg_bot_dnd_spells_2024_production
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
