CREATE DATABASE dnd_handbook_production OWNER dnd_handbook;
CREATE DATABASE dnd_handbook_production_cache OWNER dnd_handbook;
CREATE DATABASE dnd_handbook_production_queue OWNER dnd_handbook;
CREATE DATABASE dnd_handbook_production_cable OWNER dnd_handbook;
